# Generated by Django 4.0.6 on 2022-07-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_highestbid_listing_currentbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
