# Generated by Django 4.0.6 on 2022-07-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_image',
            new_name='image',
        ),
    ]
